In [1]:
import requests
import pandas as pd
import numpy as np

# API URL
url = "https://api.coingecko.com/api/v3/coins/markets"

# Your API key
api_key = "CG-ikdsyYZQvQrg3cYtn3fReiY6"

# Parameters
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 100,
    "page": 1
}

# Headers
headers = {
    "x-cg-demo-api-key": api_key
}

# Send request
response = requests.get(
    url,
    params=params,
    headers=headers
)

# Check status
print("Status code:", response.status_code)

# Convert JSON to Python data
data = response.json()

# Convert to DataFrame
df = pd.DataFrame(data)

print(df.head())

Status code: 200
            id symbol      name  \
0      bitcoin    btc   Bitcoin
1     ethereum    eth  Ethereum
2       tether   usdt    Tether
3  binancecoin    bnb       BNB
4       ripple    xrp       XRP

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   79984.000000
1  https://coin-images.coingecko.com/coins/images...    2502.190000
2  https://coin-images.coingecko.com/coins/images...       0.999989
3  https://coin-images.coingecko.com/coins/images...     757.930000
4  https://coin-images.coingecko.com/coins/images...       1.420000

      market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1606158213731                1            1606168452022  2.036625e+10
1   305371401888                2             305371401888  8.863135e+09
2   183389271343                3             188856124393  4.421059e+10
3   100928658798                4             100928656327  1.778066e+09
4    89196508856                5             142137848515  1.566641e+09

   high_24h  ...  total_supply    max_supply        ath  \
0  80147.00  ...  2.008046e+07  2.100000e+07  126080.00
1   2521.39  ...  1.220239e+08           NaN    4946.05
2      1.00  ...  1.888593e+11           NaN       1.32
3    779.70  ...  1.331619e+08  2.000000e+08    1369.99
4      1.43  ...  9.998563e+10  1.000000e+11       3.65

   ath_change_percentage                  ath_date        atl  \
0              -36.56088  2025-10-06T10:57:42.000Z  67.810000
1              -49.41025  2025-08-24T11:21:03.000Z   0.432979
2              -24.42047  2018-07-23T16:00:00.000Z   0.572521
3              -44.67642  2025-10-13T00:41:24.000Z   0.039818
4              -61.01971  2025-07-17T19:40:53.000Z   0.002686

   atl_change_percentage                  atl_date  \
0           1.178548e+05  2013-07-05T16:00:00.000Z
1           5.778021e+05  2015-10-19T16:00:00.000Z
2           7.466419e+01  2015-03-01T16:00:00.000Z
3           1.903396e+06  2017-10-18T16:00:00.000Z
4           5.281360e+04  2014-05-21T16:00:00.000Z

                                                 roi              last_updated
0                                               None  2026-09-06T12:26:20.000Z
1  {'times': 40.83155711655745, 'currency': 'btc'...  2026-09-06T12:26:20.000Z
2                                               None  2026-09-06T12:26:20.000Z
3                                               None  2026-09-06T12:26:20.000Z
4                                               None  2026-09-06T12:26:20.000Z

[5 rows x 26 columns]

In [2]:
df.shape

(100, 26)

In [3]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,79984.000000,1606158213731,1,1606168452022,2.036625e+10,80147.000000,...,2.008046e+07,2.100000e+07,126080.000000,-36.56088,2025-10-06T10:57:42.000Z,67.810000,1.178548e+05,2013-07-05T16:00:00.000Z,None,2026-09-06T12:26:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2502.190000,305371401888,2,305371401888,8.863135e+09,2521.390000,...,1.220239e+08,NaN,4946.050000,-49.41025,2025-08-24T11:21:03.000Z,0.432979,5.778021e+05,2015-10-19T16:00:00.000Z,"{'times': 40.83155711655745, 'currency': 'btc'...",2026-09-06T12:26:20.000Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999989,183389271343,3,188856124393,4.421059e+10,1.000000,...,1.888593e+11,NaN,1.320000,-24.42047,2018-07-23T16:00:00.000Z,0.572521,7.466419e+01,2015-03-01T16:00:00.000Z,None,2026-09-06T12:26:20.000Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,757.930000,100928658798,4,100928656327,1.778066e+09,779.700000,...,1.331619e+08,2.000000e+08,1369.990000,-44.67642,2025-10-13T00:41:24.000Z,0.039818,1.903396e+06,2017-10-18T16:00:00.000Z,None,2026-09-06T12:26:20.000Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.420000,89196508856,5,142137848515,1.566641e+09,1.430000,...,9.998563e+10,1.000000e+11,3.650000,-61.01971,2025-07-17T19:40:53.000Z,0.002686,5.281360e+04,2014-05-21T16:00:00.000Z,None,2026-09-06T12:26:20.000Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,official-trump,trump,Official Trump,https://coin-images.coingecko.com/coins/images...,2.350000,616355926,95,2353572656,1.952003e+08,2.420000,...,1.000000e+09,1.000000e+09,73.430000,-96.79521,2025-01-19T03:50:34.000Z,1.370000,7.174392e+01,2026-08-13T18:40:30.000Z,None,2026-09-06T12:26:20.000Z
96,vechain,vet,VeChain,https://coin-images.coingecko.com/coins/images...,0.007005,602526435,96,602526435,7.057682e+06,0.007061,...,8.598504e+10,8.671263e+10,0.280991,-97.50696,2021-04-18T17:08:21.000Z,0.001917,2.654009e+02,2020-03-12T18:29:59.000Z,"{'times': -0.01937278234173, 'currency': 'eth'...",2026-09-06T12:26:20.000Z
97,curve-dao-token,crv,Curve DAO,https://coin-images.coingecko.com/coins/images...,0.373983,581577869,97,903812731,7.586152e+07,0.390599,...,2.415903e+09,3.030303e+09,15.370000,-97.56713,2020-08-13T16:00:00.000Z,0.170749,1.190250e+02,2026-06-06T05:03:15.000Z,None,2026-09-06T12:26:20.000Z
98,flare-networks,flr,Flare,https://coin-images.coingecko.com/coins/images...,0.006670,579187755,98,710453884,3.258790e+06,0.006804,...,1.064953e+11,NaN,0.150073,-95.55546,2023-01-09T19:14:05.000Z,0.005860,1.381516e+01,2026-08-19T10:09:30.000Z,None,2026-09-06T12:26:20.000Z
99,ether-fi,ethfi,Ether.fi,https://coin-images.coingecko.com/coins/images...,0.589036,568660723,99,568660723,5.022879e+07,0.600615,...,9.653500e+08,1.000000e+09,8.530000,-93.09366,2024-03-27T15:14:46.000Z,0.266530,1.210017e+02,2026-06-05T19:19:15.000Z,None,2026-09-06T12:26:20.000Z

In [4]:
import requests
import pandas as pd

url = "https://api.coingecko.com/api/v3/coins/markets"

api_key = "CG-ikdsyYZQvQrg3cYtn3fReiY6"

headers = {
    "x-cg-demo-api-key": api_key
}

all_data = []

# Get 10 pages × 50 coins = 500 coins
for page in range(1, 11):

    params = {
        "vs_currency": "usd",
        "order": "market_cap_desc",
        "per_page": 50,
        "page": page
    }

    response = requests.get(
        url,
        params=params,
        headers=headers
    )

    print("Page:", page, "Status:", response.status_code)

    data = response.json()

    all_data.extend(data)

# Convert to DataFrame
df = pd.DataFrame(all_data)

print("Total rows:", len(df))
print(df.head())

Page: 1 Status: 200
Page: 2 Status: 200
Page: 3 Status: 200
Page: 4 Status: 200
Page: 5 Status: 200
Page: 6 Status: 200
Page: 7 Status: 200
Page: 8 Status: 200
Page: 9 Status: 200
Page: 10 Status: 200
Total rows: 500
            id symbol      name  \
0      bitcoin    btc   Bitcoin
1     ethereum    eth  Ethereum
2       tether   usdt    Tether
3  binancecoin    bnb       BNB
4       ripple    xrp       XRP

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   79986.000000
1  https://coin-images.coingecko.com/coins/images...    2502.690000
2  https://coin-images.coingecko.com/coins/images...       0.999967
3  https://coin-images.coingecko.com/coins/images...     757.950000
4  https://coin-images.coingecko.com/coins/images...       1.420000

      market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1606210807060              1.0             1.606221e+12  2.032945e+10
1   305405629623              2.0             3.054056e+11  8.856988e+09
2   183389288958              3.0             1.888561e+11  4.419437e+10
3   100940133246              4.0             1.009401e+11  1.778739e+09
4    89224379654              5.0             1.421823e+11  1.572437e+09

   high_24h  ...  total_supply    max_supply        ath  \
0  80147.00  ...  2.008046e+07  2.100000e+07  126080.00
1   2521.39  ...  1.220239e+08           NaN    4946.05
2      1.00  ...  1.888593e+11           NaN       1.32
3    779.70  ...  1.331619e+08  2.000000e+08    1369.99
4      1.43  ...  9.998563e+10  1.000000e+11       3.65

   ath_change_percentage                  ath_date        atl  \
0              -36.55940  2025-10-06T10:57:42.000Z  67.810000
1              -49.40017  2025-08-24T11:21:03.000Z   0.432979
2              -24.42213  2018-07-23T16:00:00.000Z   0.572521
3              -44.67451  2025-10-13T00:41:24.000Z   0.039818
4              -61.01705  2025-07-17T19:40:53.000Z   0.002686

   atl_change_percentage                  atl_date  \
0           1.178575e+05  2013-07-05T16:00:00.000Z
1           5.779171e+05  2015-10-19T16:00:00.000Z
2           7.466037e+01  2015-03-01T16:00:00.000Z
3           1.903462e+06  2017-10-18T16:00:00.000Z
4           5.281722e+04  2014-05-21T16:00:00.000Z

                                                 roi              last_updated
0                                               None  2026-09-06T12:25:20.000Z
1  {'times': 40.82549613312513, 'currency': 'btc'...  2026-09-06T12:25:20.000Z
2                                               None  2026-09-06T12:25:20.000Z
3                                               None  2026-09-06T12:25:20.000Z
4                                               None  2026-09-06T12:25:20.000Z

[5 rows x 26 columns]

In [5]:
df.shape

(500, 26)

In [6]:
df.to_csv("crypto_data.csv",index=False)

In [7]:
# cleaning crypto data
print("check missing value:",df.isna().sum())
print("-"*50)

check missing value: id                                    0
symbol                                0
name                                  0
image                                 0
current_price                         0
market_cap                            0
market_cap_rank                       2
fully_diluted_valuation               0
total_volume                          0
high_24h                              0
low_24h                               0
price_change_24h                     16
price_change_percentage_24h          16
market_cap_change_24h                16
market_cap_change_percentage_24h     16
circulating_supply                    0
total_supply                          0
max_supply                          206
ath                                   0
ath_change_percentage                 0
ath_date                              0
atl                                   0
atl_change_percentage                 0
atl_date                              0
roi                                 460
last_updated                          0
dtype: int64
--------------------------------------------------

In [8]:
#check columns
print("columns:",df.columns)
print("-"*50)

# create all columns into title case
df.columns=df.columns.str.title()
print("title:",df.columns)

columns: Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='object')
--------------------------------------------------
title: Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [9]:
df.head(2)

,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,High_24H,...,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Roi,Last_Updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,79986.00,1606210807060,1.0,1.606221e+12,2.032945e+10,80147.00,...,2.008046e+07,21000000.0,126080.00,-36.55940,2025-10-06T10:57:42.000Z,67.810000,117857.54419,2013-07-05T16:00:00.000Z,None,2026-09-06T12:25:20.000Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2502.69,305405629623,2.0,3.054056e+11,8.856988e+09,2521.39,...,1.220239e+08,NaN,4946.05,-49.40017,2025-08-24T11:21:03.000Z,0.432979,577917.14359,2015-10-19T16:00:00.000Z,"{'times': 40.82549613312513, 'currency': 'btc'...",2026-09-06T12:25:20.000Z

In [10]:
# check id columns
print("missing value:",df['Id'].isna().sum())
print("-"*50)

# check duplicated
print("duplicated:",df['Id'].duplicated().sum())
print("-"*50)


# create columns value into title case
df['Id']=df['Id'].str.title()
print("df['Id']")
print("-"*50)

#remove space
df['Id']=df['Id'].str.strip()
print("df['Id']")

missing value: 0
--------------------------------------------------
duplicated: 0
--------------------------------------------------
df['Id']
--------------------------------------------------
df['Id']

In [11]:
#check Symbol columns
# check missing value
print("missing value:",df['Symbol'].isna().sum())
print("-"*50)

# remove space
df['Symbol']=df['Symbol'].str.strip()
print("df['Symbol']")
print("-"*50)

# create upper case
df["Symbol"] = df["Symbol"].astype("string").str.strip().str.upper()
print("df['Symbol']")
print("-"*50)

# check duplicated
print("duplicated:",df["Symbol"].duplicated().sum())

# count duplicated value
print("count duplicated:",df['Symbol'].value_counts()[:20])

missing value: 0
--------------------------------------------------
df['Symbol']
--------------------------------------------------
df['Symbol']
--------------------------------------------------
duplicated: 6
count duplicated: Symbol
PC0000023    2
SAFE         2
DAI          2
USDF         2
M            2
USDA         2
BTC          1
AIOZ         1
PC0000101    1
EXOD         1
COW          1
ARKM         1
FXUSD        1
BULLA        1
CGUSD        1
PC0000019    1
RIF          1
SN4          1
TAG          1
SUPER        1
Name: count, dtype: Int64

In [12]:
#check Name columns
# check missing value
print("missing value:",df['Name'].isna().sum())
print("-"*50)

# check duplicated
print("duplicated:",df['Name'].duplicated().sum())
print("-"*50)

#count duplicated
print("count duplicated:",df['Name'].value_counts())
print("-"*50)

# remove

missing value: 0
--------------------------------------------------
duplicated: 1
--------------------------------------------------
count duplicated: Name
Tradable Singapore Fintech SSL            2
TAGGER                                    1
KAITO                                     1
Rootstock Infrastructure Framework        1
Tradable North America PoS Lender SSTN    1
                                         ..
USX                                       1
AINFT                                     1
Ape and Pepe                              1
Kinesis Silver                            1
Loaded Lions                              1
Name: count, Length: 499, dtype: int64
--------------------------------------------------

In [13]:
df.head(1)

,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,High_24H,...,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Roi,Last_Updated
0,Bitcoin,BTC,Bitcoin,https://coin-images.coingecko.com/coins/images...,79986.0,1606210807060,1.0,1.606221e+12,2.032945e+10,80147.0,...,20080456.0,21000000.0,126080.0,-36.5594,2025-10-06T10:57:42.000Z,67.81,117857.54419,2013-07-05T16:00:00.000Z,None,2026-09-06T12:25:20.000Z

In [14]:
# check Image columns
# check missing value
print("missing value:",df['Image'].isna().sum())
print("-"*50)

#chack duplicated value
print("duplicated:",df['Image'].duplicated().sum())
print("-"*50)

#check unique
print("unique:",df['Image'].unique())
print("-"*50)

#remove space
df['Image']=df['Image'].str.split()
print("df['Image']")

missing value: 0
--------------------------------------------------
duplicated: 0
--------------------------------------------------
unique: ['https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400'
 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628'
 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661'
 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970'
 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442'
 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602'
 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756'
 'https://coin-images.coingecko.com/coins/images/1094/large/photo_2026-04-13_09-59-16.png?1776048311'
 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954'
 'https://coin-images.coingecko.com/coins/images/486/large/Brandmark-Yellow_%281%29.png?1785810558'
 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300'
 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409'
 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191'
 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460'
 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683'
 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405'
 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096'
 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607'
 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090'
 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350'
 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932'
 'https://coin-images.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996'
 'https://coin-images.coingecko.com/coins/images/12504/large/uniswap-logo.png?1720676669'
 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299'
 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059'
 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002'
 'https://coin-images.coingecko.com/coins/images/2/large/litecoin.png?1696501400'
 'https://coin-images.coingecko.com/coins/images/17980/large/Gram_Circular_Badge.png?1781524778'
 'https://coin-images.coingecko.com/coins/images/3688/large/hbar.png?1696504364'
 'https://coin-images.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png?1696512369'
 'https://coin-images.coingecko.com/coins/images/26375/large/sui-ocean-square.png?1727791290'
 'https://coin-images.coingecko.com/coins/images/51281/large/GDN_USDG_Token_200x200.png?1730484111'
 'https://coin-images.coingecko.com/coins/images/11939/large/shiba.png?1696511800'
 'https://coin-images.coingecko.com/coins/images/10365/large/near.jpg?1696510367'
 'https://coin-images.coingecko.com/coins/images/31212/large/PYUSD_Token_Logo_2x.png?1765987788'
 'https://coin-images.coingecko.com/coins/images/36291/large/blackrock.png?1711013223'
 'https://coin-images.coingecko.com/coins/images/7310/large/cro_token_logo.png?1696507599'
 'https://coin-images.coingecko.com/coins/images/10481/large/logo.png?1774627372'
 'https://coin-images.coingecko.com/coins/images/51054/large/Hashnote_SDYC_200x200.png?1730370965'
 'https://coin-images.coingecko.com/coins/images/53247/large/square-bg-transparent.png?1752637478'
 'https://coin-images.coingecko.com/coins/images/39651/large/RLUSD_200x200_%281%29.png?1727376633'
 'https://coin-images.coingecko.com/coins/images/4463/large/WeChat_Image_20220118095654.png?1696505053'
 'https://coin-images.coingecko.com/coins/images/28452/large/ARUsPeNQ_400x400.jpeg?1696527447'
 'https://coin-images.coingecko.com/coins/images/31700/large/usdy_%281%29.png?1696530524'
 'https://coin-images.coingecko.com/coins/images/69040/large/_ASTER.png?1757326782'
 'https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354'
 'https://coin-images.coingecko.com/coins/images/30980/large/MNT_Token_Logo.png?1765516974'
 'https://coin-images.coingecko.com/coins/images/9519/large/asset-paxg.png?1785284785'
 'https://coin-images.coingecko.com/coins/images/26580/large/ONDO.png?1696525656'
 'https://coin-images.coingecko.com/coins/images/50767/large/wlfi.png?1756438915'
 'https://coin-images.coingecko.com/coins/images/29837/large/Morpho-token-icon.png?1726771230'
 'https://coin-images.coingecko.com/coins/images/36530/large/ethena.png?1711701436'
 'https://coin-images.coingecko.com/coins/images/39925/large/sky.jpg?1724827980'
 'https://coin-images.coingecko.com/coins/images/12171/large/polkadot.jpg?1766533446'
 'https://coin-images.coingecko.com/coins/images/67164/large/pump.jpg?1751949376'
 'https://coin-images.coingecko.com/coins/images/31069/large/worldcoin.jpeg?1696529903'
 'https://coin-images.coingecko.com/coins/images/29850/large/pepe-token.jpeg?1696528776'
 'https://coin-images.coingecko.com/coins/images/35491/large/Frame_1321318576.png?1708908626'
 'https://coin-images.coingecko.com/coins/images/14495/large/Internet_Computer_logo.png?1696514180'
 'https://coin-images.coingecko.com/coins/images/25380/large/UUSD.jpg?1696524513'
 'https://coin-images.coingecko.com/coins/images/11610/large/Bitget_logo.png?1736925727'
 'https://coin-images.coingecko.com/coins/images/102172077/large/USDGO_%287%29.png?1771437018'
 'https://coin-images.coingecko.com/coins/images/54558/large/ff_200_X_200.png?1740741076'
 'https://coin-images.coingecko.com/coins/images/68227/large/bfusd.png?1755132827'
 'https://coin-images.coingecko.com/coins/images/16547/large/arb.jpg?1721358242'
 'https://coin-images.coingecko.com/coins/images/71157/large/united-stables-logo.jpg?1766061640'
 'https://coin-images.coingecko.com/coins/images/102172591/large/Fund_eurSAF0.png?1774104814'
 'https://coin-images.coingecko.com/coins/images/453/large/ethereum-classic-logo.png?1696501717'
 'https://coin-images.coingecko.com/coins/images/71205/large/BTW_Token_200x200.png?1786291907'
 'https://coin-images.coingecko.com/coins/images/71121/large/lighter.png?1765888098'
 'https://coin-images.coingecko.com/coins/images/54342/large/pi_network.jpg?1739347576'
 'https://coin-images.coingecko.com/coins/images/32440/large/pol.png?1759114181'
 'https://coin-images.coingecko.com/coins/images/8183/large/200X200.png?1735246724'
 'https://coin-images.coingecko.com/coins/images/1047/large/sa9z79.png?1696502152'
 'https://coin-images.coingecko.com/coins/images/56040/large/bcap_logo_200.png?1748088291'
 'https://coin-images.coingecko.com/coins/images/3370/large/5ZOu7brX_400x400.jpg?1696504070'
 'https://coin-images.coingecko.com/coins/images/11095/large/JUST.jpg?1696511035'
 'https://coin-images.coingecko.com/coins/images/39657/large/EUTBL.png?1723517425'
 'https://coin-images.coingecko.com/coins/images/34188/large/jup.png?1704266489'
 'https://coin-images.coingecko.com/coins/images/19/large/dash-logo.png?1696501423'
 'https://coin-images.coingecko.com/coins/images/4380/large/download.png?1696504978'
 'https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525'
 'https://coin-images.coingecko.com/coins/images/25751/large/kaspa-icon-exchanges.png?1696524837'
 'https://coin-images.coingecko.com/coins/images/3695/large/CG-nexo-token-200x200_2x.png?1730414360'
 'https://coin-images.coingecko.com/coins/images/54023/large/VVV_Token_Transparent.png?1741856877'
 'https://coin-images.coingecko.com/coins/images/70445/large/JTRSY.png?1762078582'
 'https://coin-images.coingecko.com/coins/images/11636/large/rndr.png?1696511529'
 'https://coin-images.coingecko.com/coins/images/35012/large/Invesco_icon_lg.png?1780816895'
 'https://coin-images.coingecko.com/coins/images/69242/large/stable-logotype-framed-square-light.png?1762753913'
 'https://coin-images.coingecko.com/coins/images/12632/large/pancakeswap-cake-logo_%281%29.png?1696512440'
 'https://coin-images.coingecko.com/coins/images/70446/large/jaaa.png?1762078666'
 'https://coin-images.coingecko.com/coins/images/30663/large/gho-token-logo.png?1720517092'
 'https://coin-images.coingecko.com/coins/images/12817/large/filecoin.png?1696512609'
 'https://coin-images.coingecko.com/coins/images/102174571/large/jhitvkisdq8fhxvimdkpcw7y3dx5.?1784093932'
 'https://coin-images.coingecko.com/coins/images/5111/large/Beldex.png?1696505631'
 'https://coin-images.coingecko.com/coins/images/53746/large/trump.png?1737171561'
 'https://coin-images.coingecko.com/coins/images/1167/large/VET.png?1742383283'
 'https://coin-images.coingecko.com/coins/images/12124/large/Curve.png?1696511967'
 'https://coin-images.coingecko.com/coins/images/28624/large/FLR-icon200x200.png?1696527609'
 'https://coin-images.coingecko.com/coins/images/35958/large/etherfi.jpeg?1710254562'
 'https://coin-images.coingecko.com/coins/images/2912/large/xdc-icon.png?1696503661'
 'https://coin-images.coingecko.com/coins/images/52622/large/PUDGY_PENGUINS_PENGU_PFP.png?1733809110'
 'https://coin-images.coingecko.com/coins/images/38272/large/USD0LOGO.png?1716962811'
 'https://coin-images.coingecko.com/coins/images/31745/large/token.png?1696530564'
 'https://coin-images.coingecko.com/coins/images/31401/large/centeredcoin_%281%29.png?1737048493'
 'https://coin-images.coingecko.com/coins/images/26455/large/Aptos-Network-Profile-Picture_%281%29.png?1788259511'
 'https://coin-images.coingecko.com/coins/images/66486/large/YLDS.png?1772560579'
 'https://coin-images.coingecko.com/coins/images/69848/large/%E5%B8%81%E5%AE%89%E4%BA%BA%E7%94%9F.png?1759839225'
 'https://coin-images.coingecko.com/coins/images/12882/large/Other_200x200.png?1738782212'
 'https://coin-images.coingecko.com/coins/images/2069/large/Stacks_Logo_png.png?1709979332'
 'https://coin-images.coingecko.com/coins/images/3449/large/tusd.png?1696504140'
 'https://coin-images.coingecko.com/coins/images/52804/large/76357aa8-4ef7-446c-bad3-a3f944eeec7a.jpeg?1758277468'
 'https://coin-images.coingecko.com/coins/images/66154/large/Hastra_Icon.png?1748497203'
 'https://coin-images.coingecko.com/coins/images/26045/large/EURC.png?1769615705'
 'https://coin-images.coingecko.com/coins/images/34057/large/LOGOMARK.png?1708356054'
 'https://coin-images.coingecko.com/coins/images/66657/large/A7A5_200.png?1750163839'
 'https://coin-images.coingecko.com/coins/images/31924/large/pyth.png?1701245725'
 'https://coin-images.coingecko.com/coins/images/5681/large/ASI.png?1719827289'
 'https://coin-images.coingecko.com/coins/images/28206/large/ftxG9_TJ_400x400.jpeg?1696527208'
 'https://coin-images.coingecko.com/coins/images/71015/large/midnight.png?1765193080'
 'https://coin-images.coingecko.com/coins/images/31967/large/tia.jpg?1696530772'
 'https://coin-images.coingecko.com/coins/images/69121/large/ff.png?1757573403'
 'https://coin-images.coingecko.com/coins/images/15069/large/Pendle_Logo_Normal-03.png?1696514728'
 'https://coin-images.coingecko.com/coins/images/13573/large/Lido_DAO.png?1696513326'
 'https://coin-images.coingecko.com/coins/images/29788/large/kau-currency-ticker.png?1696528718'
 'https://coin-images.coingecko.com/coins/images/6799/large/BSV.png?1696507128'
 'https://coin-images.coingecko.com/coins/images/69108/large/unibase.png?1757501820'
 'https://coin-images.coingecko.com/coins/images/29023/large/OUSG.png?1696527993'
 'https://coin-images.coingecko.com/coins/images/31079/large/FDUSD_icon_black.png?1731097953'
 'https://coin-images.coingecko.com/coins/images/28205/large/Sei_Logo_-_Transparent.png?1696527207'
 'https://coin-images.coingecko.com/coins/images/13928/large/PSigc4ie_400x400.jpg?1696513668'
 'https://coin-images.coingecko.com/coins/images/12424/large/RSFOmQ.png?1696512245'
 'https://coin-images.coingecko.com/coins/images/71688/large/CRY25-3266080_StableCoinLogo.png?1768922282'
 'https://coin-images.coingecko.com/coins/images/102172243/large/apxUSD.png?1772448502'
 'https://coin-images.coingecko.com/coins/images/68410/large/akedo.png?1755678461'
 'https://coin-images.coingecko.com/coins/images/38927/large/mon.png?1766029057'
 'https://coin-images.coingecko.com/coins/images/662/large/logo_square_simple_300px.png?1696501854'
 'https://coin-images.coingecko.com/coins/images/14483/large/token_OHM_%281%29.png?1696514169'
 'https://coin-images.coingecko.com/coins/images/70426/large/KITE-ICON.png?1762328605'
 'https://coin-images.coingecko.com/coins/images/67072/large/3D_ONYC.png?1779524172'
 'https://coin-images.coingecko.com/coins/images/22457/large/btt_logo.png?1696521780'
 'https://coin-images.coingecko.com/coins/images/329/large/dcr.png?1762890696'
 'https://coin-images.coingecko.com/coins/images/28600/large/bonk.jpg?1696527587'
 'https://coin-images.coingecko.com/coins/images/8284/large/01_LunaClassic_color.png?1696508486'
 'https://coin-images.coingecko.com/coins/images/55857/large/USDai_Token_Full_Glyph.png?1755229050'
 'https://coin-images.coingecko.com/coins/images/68773/large/pieverse.png?1756546685'
 'https://coin-images.coingecko.com/coins/images/976/large/Tezos-logo.png?1696502091'
 'https://coin-images.coingecko.com/coins/images/13079/large/3vuYMbjN.png?1696512867'
 'https://coin-images.coingecko.com/coins/images/39284/large/AUSD_1024px.png?1764684132'
 'https://coin-images.coingecko.com/coins/images/19785/large/ENS.jpg?1727872989'
 'https://coin-images.coingecko.com/coins/images/66489/large/Plasma-symbol-green-1.png?1755142558'
 'https://coin-images.coingecko.com/coins/images/11085/large/Trust.png?1696511026'
 'https://coin-images.coingecko.com/coins/images/20665/large/TGBfBt6Y2Dm3RHdNpZAdqywBsvfdysf834.jpeg?1749135788'
 'https://coin-images.coingecko.com/coins/images/51232/large/_syrup_token_logo.png?1747292046'
 'https://coin-images.coingecko.com/coins/images/66291/large/Points_Program_Group_91.png?1749676055'
 'https://coin-images.coingecko.com/coins/images/30118/large/crvusd.jpg?1746670973'
 'https://coin-images.coingecko.com/coins/images/25244/large/Token.png?1774456081'
 'https://coin-images.coingecko.com/coins/images/54970/large/Untitled_design.png?1742941268'
 'https://coin-images.coingecko.com/coins/images/29789/large/kag-currency-ticker.png?1696528719'
 'https://coin-images.coingecko.com/coins/images/39614/large/APEPE_200.png?1723142351'
 'https://coin-images.coingecko.com/coins/images/15687/large/AINFT.png?1761099340'
 'https://coin-images.coingecko.com/coins/images/68429/large/Solstice_Icons_for_DEX_512x512_USX.png?1755718377'
 'https://coin-images.coingecko.com/coins/images/33228/large/jto.png?1701137022'
 'https://coin-images.coingecko.com/coins/images/40094/large/Grass.jpg?1725697048'
 'https://coin-images.coingecko.com/coins/images/13827/large/bnb48.png?1696513570'
 'https://coin-images.coingecko.com/coins/images/102174280/large/cashcat-logo.jpg?1782922765'
 'https://coin-images.coingecko.com/coins/images/102172616/large/edgex.png?1774332310'
 'https://coin-images.coingecko.com/coins/images/55684/large/coingeckoupdate.png?1755203747'
 'https://coin-images.coingecko.com/coins/images/26433/large/starknet.png?1696525507'
 'https://coin-images.coingecko.com/coins/images/15585/large/convex.png?1696515221'
 'https://coin-images.coingecko.com/coins/images/13422/large/LFRAX.png?1751911193'
 'https://coin-images.coingecko.com/coins/images/13397/large/Graph_Token.png?1696513159'
 'https://coin-images.coingecko.com/coins/images/33566/large/dogwifhat.jpg?1702499428'
 'https://coin-images.coingecko.com/coins/images/13876/large/JASMY200x200.jpg?1696513620'
 'https://coin-images.coingecko.com/coins/images/10775/large/COMP.png?1696510737'
 'https://coin-images.coingecko.com/coins/images/102176647/large/5ou9sb7h478ezv28urbjpzf1fl3e.?1788401429'
 'https://coin-images.coingecko.com/coins/images/66150/large/tradable.jpg?1748488921'
 'https://coin-images.coingecko.com/coins/images/102175246/large/1000299474.png?1785934648'
 'https://coin-images.coingecko.com/coins/images/39901/large/KAIA.png?1724734368'
 'https://coin-images.coingecko.com/coins/images/692/large/IOTA_Thumbnail_%281%29.png?1743772896'
 'https://coin-images.coingecko.com/coins/images/4343/large/oRt6SiEN_400x400.jpg?1696504946'
 'https://coin-images.coingecko.com/coins/images/37441/large/eigencloud.jpg?1751003565'
 'https://coin-images.coingecko.com/coins/images/37052/large/zbcn.jpeg?1713168241'
 'https://coin-images.coingecko.com/coins/images/33415/large/eurcv_%281%29.png?1701752017'
 'https://coin-images.coingecko.com/coins/images/102172527/large/apyUSD.png?1773763322'
 'https://coin-images.coingecko.com/coins/images/71792/large/usat_logo_200x200.png?1769440161'
 'https://coin-images.coingecko.com/coins/images/2117/large/YJUrRy7r_400x400.png?1696503083'
 'https://coin-images.coingecko.com/coins/images/50891/large/fart.jpg?1729503972'
 'https://coin-images.coingecko.com/coins/images/2538/large/theta-token-logo.png?1696503349'
 'https://coin-images.coingecko.com/coins/images/68339/large/Coingecko_-_PFP.png?1755694420'
 'https://coin-images.coingecko.com/coins/images/55974/large/T7asvmCb_400x400.jpg?1747902862'
 'https://coin-images.coingecko.com/coins/images/31844/large/ULTIMA-200x200.png?1763090865'
 'https://coin-images.coingecko.com/coins/images/71124/large/%E6%9C%AA%E5%91%BD%E5%90%8D%E7%9A%84%E8%AE%BE%E8%AE%A1_%2821%29.png?1765893957'
 'https://coin-images.coingecko.com/coins/images/39666/large/USTB.png?1723541269'
 'https://coin-images.coingecko.com/coins/images/1899/large/tel.png?1696502892'
 'https://coin-images.coingecko.com/coins/images/13029/large/axie_infinity_logo.png?1696512817'
 'https://coin-images.coingecko.com/coins/images/12785/large/akash-logo.png?1696512580'
 'https://coin-images.coingecko.com/coins/images/52889/large/Token_Logo.png?1734601695'
 'https://coin-images.coingecko.com/coins/images/102172590/large/Fund_usdSAFO.png?1774104804'
 'https://coin-images.coingecko.com/coins/images/24210/large/onyxlogo.jpg?1696523397'
 'https://coin-images.coingecko.com/coins/images/31193/large/NPC_200x200.png?1696530021'
 'https://coin-images.coingecko.com/coins/images/66798/large/tradable.jpg?1750576460'
 'https://coin-images.coingecko.com/coins/images/6595/large/THORChain_RUNE_Token.png?1782452363'
 'https://coin-images.coingecko.com/coins/images/8545/large/mexc.jpg?1747142259'
 'https://coin-images.coingecko.com/coins/images/67434/large/200x200_%281%29.png?1752777433'
 'https://coin-images.coingecko.com/coins/images/71033/large/Ticker_STRCx__Company_Name_Strategy_PP_Variable__size_200x200.png?1765380234'
 'https://coin-images.coingecko.com/coins/images/67399/large/Logo-Vision-Symbol-BG-Green.png?1752676915'
 'https://coin-images.coingecko.com/coins/images/480/large/NEO_512_512.png?1696501735'
 'https://coin-images.coingecko.com/coins/images/1877/large/TRAC.jpg?1696502873'
 'https://coin-images.coingecko.com/coins/images/66811/large/H_tokenLogo_original.png?1750581252'
 'https://coin-images.coingecko.com/coins/images/68725/large/gusd-logo.jpeg?1757681286'
 'https://coin-images.coingecko.com/coins/images/878/large/decentraland-mana.png?1696502010'
 'https://coin-images.coingecko.com/coins/images/70974/large/seeker-logo.jpg?1764922774'
 'https://coin-images.coingecko.com/coins/images/70921/large/zama.png?1764591992'
 'https://coin-images.coingecko.com/coins/images/16646/large/Logo_final-22.png?1696516207'
 'https://coin-images.coingecko.com/coins/images/8834/large/CHZ_Token_updated.png?1696508986'
 'https://coin-images.coingecko.com/coins/images/15662/large/GoMining_Logo.webp?1769225542'
 'https://coin-images.coingecko.com/coins/images/24383/large/APECOIN.png?1756551529'
 'https://coin-images.coingecko.com/coins/images/13905/large/sfp.png?1696513647'
 'https://coin-images.coingecko.com/coins/images/35148/large/shuffle_token_200x200.png?1707552712'

In [15]:
# check Current_Price columns
print("missing value:",df['Current_Price'].isna().sum())
print("="*50)

# check duplicated
print("duplicated:",df['Current_Price'].duplicated().sum())
#count duplicated
print("count duplicated:",df['Current_Price'].value_counts())

# check zero value
print("count zero:",(df['Current_Price']==0).sum())
print("="*50)

# check negetive value
print("negative value:",(df['Current_Price'] < 0).sum())

missing value: 0
==================================================
duplicated: 33
count duplicated: Current_Price
1.000000e+00    23
1.140000e+00     3
1.120000e+00     3
1.180000e+00     2
1.420000e+00     2
                ..
3.447610e-01     1
4.524980e-01     1
9.994530e-01     1
2.416060e-07     1
1.502830e-03     1
Name: count, Length: 467, dtype: int64
count zero: 0
==================================================
negative value: 0

In [16]:

df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [17]:
df.head(1)

,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,High_24H,...,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Roi,Last_Updated
0,Bitcoin,BTC,Bitcoin,[https://coin-images.coingecko.com/coins/image...,79986.0,1606210807060,1.0,1.606221e+12,2.032945e+10,80147.0,...,20080456.0,21000000.0,126080.0,-36.5594,2025-10-06T10:57:42.000Z,67.81,117857.54419,2013-07-05T16:00:00.000Z,None,2026-09-06T12:25:20.000Z

In [18]:
# check Market_Cap columns
print("missing value:",df['Market_Cap'].isna().sum())
print("-"*50)

#check duplicated
print("duplicated:",df['Market_Cap'].duplicated().sum())
print("-"*50)

#check zero value
print("zero value:",(df['Market_Cap'] == 0).sum())
print("-"*50)

# check negative value
print("zero value:",(df['Market_Cap'] < 0).sum())
print("-"*50)

#  check  data type
print("data type:",df['Market_Cap'].dtype)

missing value: 0
--------------------------------------------------
duplicated: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
data type: int64

In [19]:
# check Market_Cap_Rank columns
# check missing value
print("missing value:",df['Market_Cap_Rank'].isna().sum())
print("-"*50)

# fill missing value using median
df['Market_Cap_Rank']=df['Market_Cap_Rank'].fillna(df['Market_Cap_Rank'].median())
print("fill missing value:",df['Market_Cap_Rank'])
print("-"*50)

# after fill check missing value
print("missing value:",df['Market_Cap_Rank'].isna().sum())
print("-"*50)

#  check  duplicated value
print("duplicated:",df['Market_Cap_Rank'].duplicated().sum())
print("count duplicated:",df['Market_Cap_Rank'].value_counts())

# check zero value
print("zero value:",(df['Market_Cap_Rank'] == 0).sum())
print("-"*50)

# check negative value
print("negative value:",(df['Market_Cap_Rank'] < 0).sum())

missing value: 2
--------------------------------------------------
fill missing value: 0        1.0
1        2.0
2        3.0
3        4.0
4        5.0
       ...
495    482.0
496    483.0
497    484.0
498    485.0
499    486.0
Name: Market_Cap_Rank, Length: 500, dtype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
duplicated: 13
count duplicated: Market_Cap_Rank
351.0    2
9.0      2
386.0    2
348.0    2
229.0    2
        ..
159.0    1
158.0    1
157.0    1
156.0    1
486.0    1
Name: count, Length: 487, dtype: int64
zero value: 0
--------------------------------------------------
negative value: 0

In [20]:
df.head(1)

,Id,Symbol,Name,Image,Current_Price,Market_Cap,Market_Cap_Rank,Fully_Diluted_Valuation,Total_Volume,High_24H,...,Total_Supply,Max_Supply,Ath,Ath_Change_Percentage,Ath_Date,Atl,Atl_Change_Percentage,Atl_Date,Roi,Last_Updated
0,Bitcoin,BTC,Bitcoin,[https://coin-images.coingecko.com/coins/image...,79986.0,1606210807060,1.0,1.606221e+12,2.032945e+10,80147.0,...,20080456.0,21000000.0,126080.0,-36.5594,2025-10-06T10:57:42.000Z,67.81,117857.54419,2013-07-05T16:00:00.000Z,None,2026-09-06T12:25:20.000Z

In [21]:
# check Fully_Diluted_Valuation columns
print("missing value:",df['Fully_Diluted_Valuation'].isna().sum())
print("-"*50)

# cheeck duplicated
print("duplicated:",df['Fully_Diluted_Valuation'].duplicated().sum())
# count duplicateed
print("count duplicated:",df['Fully_Diluted_Valuation'].value_counts())

# check zero value
print("zero value:",(df['Fully_Diluted_Valuation'] == 0).sum())
print("-"*50)
# convert zero value into nan
df['Fully_Diluted_Valuation']=df['Fully_Diluted_Valuation'].replace(0,np.nan)
print("df['Fully_Diluted_Valuation']")

missing value: 0
--------------------------------------------------
duplicated: 1
count duplicated: Fully_Diluted_Valuation
0.000000e+00    2
1.606221e+12    1
1.715678e+08    1
3.117076e+08    1
7.547861e+07    1
               ..
2.379042e+08    1
2.393120e+08    1
2.422788e+08    1
2.416075e+08    1
1.502956e+08    1
Name: count, Length: 499, dtype: int64
zero value: 2
--------------------------------------------------
df['Fully_Diluted_Valuation']

In [22]:
# after coverrt check missing value
print("missing value:",df['Fully_Diluted_Valuation'].isna().sum())
print("-"*50)

# fill them into using median
df['Fully_Diluted_Valuation']=df['Fully_Diluted_Valuation'].fillna(df['Fully_Diluted_Valuation'].median())
print("fill missing value:",df['Fully_Diluted_Valuation'])

missing value: 2
--------------------------------------------------
fill missing value: 0      1.606221e+12
1      3.054056e+11
2      1.888561e+11
3      1.009401e+11
4      1.421823e+11
           ...
495    2.461298e+08
496    4.776895e+07
497    4.625038e+07
498    6.480976e+07
499    1.502956e+08
Name: Fully_Diluted_Valuation, Length: 500, dtype: float64

In [23]:
print("missing value:",df['Fully_Diluted_Valuation'].isna().sum())
print("*"*50)
# check negetive value
print("negative value:",(df['Fully_Diluted_Valuation'] < 0).sum())

missing value: 0
**************************************************
negative value: 0

In [24]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [25]:
# check Total_Volume columns
print("missing value:",df['Total_Volume'].isna().sum())
print("-"*50)

# check duplicated
print("check duplicated:",df['Total_Volume'].duplicated().sum())
print("-"*50)

# check data type
print("data type:",df['Total_Volume'].dtype)
print("-"*50)

# check zero value
print("zero value:",(df['Total_Volume'] == 0).sum())
# check thair percentage
print("zero_per:",(df['Total_Volume'] == 0).mean()*100)
print("-"*50)

# covert zero value into nan
df['Total_Volume']=df['Total_Volume'].replace(0,np.nan)
print(df['Total_Volume'])

missing value: 0
--------------------------------------------------
check duplicated: 41
--------------------------------------------------
data type: float64
--------------------------------------------------
zero value: 42
zero_per: 8.4
--------------------------------------------------
0      2.032945e+10
1      8.856988e+09
2      4.419437e+10
3      1.778739e+09
4      1.572437e+09
           ...
495    1.900828e+06
496    1.724425e+06
497    9.276700e+02
498    3.839863e+06
499    2.445300e+04
Name: Total_Volume, Length: 500, dtype: float64

In [26]:
# after convert nan value check missing value
print("missing value:",df['Total_Volume'].isna().sum())
print("-"*50)

# fill them using median
df['Total_Volume']=df['Total_Volume'].fillna(df['Total_Volume'].median())
print("missing value:",df['Total_Volume'])

missing value: 42
--------------------------------------------------
missing value: 0      2.032945e+10
1      8.856988e+09
2      4.419437e+10
3      1.778739e+09
4      1.572437e+09
           ...
495    1.900828e+06
496    1.724425e+06
497    9.276700e+02
498    3.839863e+06
499    2.445300e+04
Name: Total_Volume, Length: 500, dtype: float64

In [27]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [28]:
#check High_24H columns
print("missing value:",df['High_24H'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['High_24H']==0).sum())
print("-"*50)

# convert zero value innto nan 
df['High_24H']=df['High_24H'].replace(0,np.nan)
print(df['High_24H'])

# after covert check missing value
print("missing value:",df['High_24H'].isna().sum())
print("-"*50)

# fill them using meadian
df['High_24H']=df['High_24H'].fillna(df['High_24H'].median())
print(df['High_24H'])
print("-"*50)

# check missing value
print("missing value:",df['High_24H'].isna().sum())
print("-"*50)

# check duplicated
print("check duplicated:",df['High_24H'].duplicated().sum())

missing value: 0
--------------------------------------------------
zero value: 10
--------------------------------------------------
0      80147.000000
1       2521.390000
2          1.000000
3        779.700000
4          1.430000
           ...
495        0.292096
496        0.036415
497        1.000000
498        0.006576
499        0.001517
Name: High_24H, Length: 500, dtype: float64
missing value: 10
--------------------------------------------------
0      80147.000000
1       2521.390000
2          1.000000
3        779.700000
4          1.430000
           ...
495        0.292096
496        0.036415
497        1.000000
498        0.006576
499        0.001517
Name: High_24H, Length: 500, dtype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
check duplicated: 56

In [29]:
# check Low_24H columns

# check missing value
print("missing value:",df['Low_24H'].isna().sum())
print("-"*50)

# check data type
print("data type:",df['Low_24H'].dtype)
print("-"*50)

# check zero value
print("zero value:",(df['Low_24H'] == 0).sum())
print("-"*50)

# covert them into nan 
df['Low_24H']=df['Low_24H'].replace(0,np.nan)
print('missing value:',df['Low_24H'])

missing value: 0
--------------------------------------------------
data type: float64
--------------------------------------------------
zero value: 10
--------------------------------------------------
missing value: 0      79586.000000
1       2451.620000
2          0.999881
3        754.740000
4          1.410000
           ...
495        0.225349
496        0.034887
497        0.998726
498        0.006431
499        0.001470
Name: Low_24H, Length: 500, dtype: float64

In [30]:
# after covert  check missing value
print("missing value:",df['Low_24H'].isna().sum())
print("-"*50)

# fill them using median
df['Low_24H']=df['Low_24H'].fillna(df['Low_24H'].median())
print("affter fill missing value",df['Low_24H'])

missing value: 10
--------------------------------------------------
affter fill missing value 0      79586.000000
1       2451.620000
2          0.999881
3        754.740000
4          1.410000
           ...
495        0.225349
496        0.034887
497        0.998726
498        0.006431
499        0.001470
Name: Low_24H, Length: 500, dtype: float64

In [31]:
print("missing value:",df['Low_24H'].isna().sum())
print("-"*50)
# check duplicated
print("duplicated:",df['Low_24H'].duplicated().sum())
print("-"*50)

# check data type
print("datatype:",df['Low_24H'].dtype)

missing value: 0
--------------------------------------------------
duplicated: 40
--------------------------------------------------
datatype: float64

In [32]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [33]:
# check Price_Change_24H columns
print("missing  value:",df['Price_Change_24H'].isna().sum())
# check zero value
print("zero value:",(df['Price_Change_24H'] == 0).value_counts())
#check nagative value
print("nagetive  value:",(df['Price_Change_24H'] < 0).sum())
print("-"*50)

# filling missing value using median
df['Price_Change_24H']=df['Price_Change_24H'].fillna(df['Price_Change_24H'].median())
print(df['Price_Change_24H'])
print("-"*50)

# check data type 
print("data type:",df['Price_Change_24H'].dtype)

missing  value: 16
zero value: Price_Change_24H
False    467
True      33
Name: count, dtype: int64
nagetive  value: 141
--------------------------------------------------
0      320.500000
1       47.920000
2       -0.000107
3        3.410000
4        0.016201
          ...
495      0.015668
496      0.000125
497      0.001353
498      0.000035
499      0.000028
Name: Price_Change_24H, Length: 500, dtype: float64
--------------------------------------------------
data type: float64

In [34]:
# check Price_Change_Percentage_24H columns
print("missing value:",df['Price_Change_Percentage_24H'].isna().sum())
print("-"*50)

# fill them using median
df['Price_Change_Percentage_24H']=df['Price_Change_Percentage_24H'].fillna(df['Price_Change_Percentage_24H'].median())
print(df['Price_Change_Percentage_24H'])

print("missing value:",df['Price_Change_Percentage_24H'].isna().sum())
print("-"*50)

# check nagative value
print("nagative value:",(df['Price_Change_Percentage_24H'] < 0).sum())
print("-"*50)

#check data type
print("data type:",df['Price_Change_Percentage_24H'].dtype)

missing value: 16
--------------------------------------------------
0      0.40395
1      1.94505
2     -0.01041
3      0.47163
4      1.16012
        ...
495    6.81693
496    0.35094
497    0.13551
498    0.54987
499    1.88994
Name: Price_Change_Percentage_24H, Length: 500, dtype: float64
missing value: 0
--------------------------------------------------
nagative value: 141
--------------------------------------------------
data type: float64

In [35]:
# check Market_Cap_Change_24H columns
print("missinng value:",df['Market_Cap_Change_24H'].isna().sum())
print("-"*50)

# fill them using median
df['Market_Cap_Change_24H']=df['Market_Cap_Change_24H'].fillna(df['Market_Cap_Change_24H'].median())
print(df['Market_Cap_Change_24H'])

# check zero value
print("zero value:",(df['Market_Cap_Change_24H'] == 0).sum())
# check nagative value
print("nagative value:",(df['Market_Cap_Change_24H'] < 0).sum())
print("-"*50)

# check data type
print("data type:",df['Market_Cap_Change_24H'].dtype)

missinng value: 16
--------------------------------------------------
0      6.537168e+09
1      5.871785e+09
2     -1.679826e+07
3      4.629835e+08
4      1.051732e+09
           ...
495    3.094618e+06
496    1.151770e+05
497   -6.562449e+05
498    2.684340e+05
499    8.590830e+05
Name: Market_Cap_Change_24H, Length: 500, dtype: float64
zero value: 32
nagative value: 137
--------------------------------------------------
data type: float64

In [36]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [37]:
# check Market_Cap_Change_Percentage_24H columns 

print("missing value:",df['Market_Cap_Change_Percentage_24H'].isna().sum())
print("-"*50)

# fill missing value
df['Market_Cap_Change_Percentage_24H']=df['Market_Cap_Change_Percentage_24H'].fillna(df['Market_Cap_Change_Percentage_24H'].median())
print(df['Market_Cap_Change_Percentage_24H'])

# check data type
print("data type:",(df['Market_Cap_Change_Percentage_24H'] == 0).sum())

missing value: 16
--------------------------------------------------
0      0.40866
1      1.96031
2     -0.00916
3      0.46078
4      1.19281
        ...
495    7.08636
496    0.24948
497   -1.39904
498    0.58460
499    1.89846
Name: Market_Cap_Change_Percentage_24H, Length: 500, dtype: float64
data type: 34

In [38]:
# check Circulating_Supply columns
print("missing value:",df['Circulating_Supply'].isna().sum())
print("-"*50)

# check  data type
print("data type:",df['Circulating_Supply'].dtype)
print("-"*50)

# check zero value
print("zero value:",(df['Circulating_Supply'] == 0).sum())
print("-"*50)

# nagetive value
print("nagetive value:",(df['Circulating_Supply'] < 0).sum())

# Infinite values
print("Infinite value:", np.isinf(df['Circulating_Supply']).sum())

missing value: 0
--------------------------------------------------
data type: float64
--------------------------------------------------
zero value: 0
--------------------------------------------------
nagetive value: 0
Infinite value: 0

In [39]:
# check Total_Supply columns
# check datatype
print("data type:",df['Total_Supply'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Total_Supply'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Total_Supply'] == 0).sum())
print("-"*50)

#  check nagetive value
print("nagetive value:",(df['Total_Supply'] < 0).sum())

# Infinite values
print("Infinite value:", np.isinf(df['Total_Supply']).sum())

# check unique value
print("unique:",df['Total_Supply'].unique())

data type: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
nagetive value: 0
Infinite value: 0
unique: [2.00804560e+07 1.22023858e+08 1.88859329e+11 1.33161861e+08
 9.99856277e+10 7.45602516e+10 6.33549057e+08 9.49376222e+10
 2.22906501e+10 1.69176002e+07 9.55307079e+08 1.55802816e+11
 1.14240854e+12 1.88010700e+07 9.82336230e+09 1.00000000e+09
 2.93606018e+08 9.85239504e+08 4.50000000e+10 5.00017868e+10
 2.00853874e+07 4.61038657e+09 8.90460420e+08 3.95391045e+10
 4.35167510e+09 4.24804590e+09 7.75801606e+07 5.24432421e+09
 5.00000000e+10 4.63441061e+08 1.00000000e+10 3.26267458e+09
 5.89496239e+14 1.30558716e+09 2.93579896e+09 2.83228287e+09
 9.89042441e+10 7.07747089e+05 2.30898805e+09 5.41108823e+09
 2.40715138e+09 2.10000000e+07 1.92035425e+09 7.80396812e+09
 1.60000000e+07 6.21931679e+09 4.32503322e+05 1.00000000e+11
 1.50000000e+10 2.34626651e+10 1.70149872e+09 8.35446237e+11
 4.20690000e+14 8.98232729e+14 5.56240628e+08 1.47012477e+09
 9.10920875e+08 1.35545441e+09 1.34408311e+09 1.32000000e+09
 1.27749911e+09 1.04568748e+09 1.58080489e+08 1.71410471e+10
 1.07094548e+10 1.18869816e+08 1.42155021e+08 9.11211100e+06
 1.46124930e+07 8.18874304e+09 7.18027528e+08 6.86243122e+09
 1.28282433e+07 9.03912445e+09 5.29185592e+08 2.76846793e+10
 8.09519206e+07 7.17141157e+08 5.33532275e+08 6.91908121e+07
 3.32454315e+08 6.78300455e+08 6.99000000e+08 1.95709108e+09
 7.12104762e+08 9.93947027e+09 8.59850412e+10 2.41590286e+09
 1.06495284e+11 9.65350000e+08 3.80656864e+10 7.67228433e+10
 5.49053443e+08 1.97368509e+09 9.30987335e+08 1.20828776e+09
 5.23552100e+08 1.00000000e+08 1.86429912e+09 4.94515083e+08
 4.82511649e+08 9.49784754e+10 3.99980051e+08 3.92317831e+10
 2.71438455e+09 2.40000000e+10 1.17658668e+09 2.81527448e+08
 2.38622783e+06 2.00798938e+07 2.89258556e+06 3.34420598e+08
 5.55000000e+08 1.99007300e+10 3.23995310e+08 3.29882652e+08
 1.00682925e+11 3.00000000e+06 1.98245907e+07 2.61806673e+08
 9.90000000e+14 1.75917742e+07 8.79945342e+13 6.45034385e+12
 2.82935940e+08 1.11541166e+09 5.23743336e+09 2.60078542e+08
 3.39432648e+09 1.24467749e+09 2.29413207e+08 2.49803767e+08
 4.29496730e+09 9.99904783e+08 3.77709693e+06 2.10000000e+14
 9.90105593e+14 2.38034755e+08 3.37999760e+06 9.88287276e+08
 9.99940362e+08 9.99890927e+07 2.19320046e+08 1.16129954e+10
 9.98926392e+08 1.00000000e+07 9.91432221e+08 2.02500000e+08
 6.41252763e+09 4.97498147e+09 6.56524660e+07 1.84012626e+09
 9.99987741e+10 1.61288990e+08 1.36533667e+08 1.84317598e+08
 9.81352443e+08 9.99974443e+08 9.99809218e+09 1.00000000e+05
 1.55513065e+08 2.70000000e+08 2.97544681e+08 1.50000000e+09
 1.60822890e+08 5.34024226e+10 8.05012652e+09 1.62500000e+08
 3.53992702e+08 4.09024834e+08 2.81712541e+06 4.20000000e+09
 5.00000000e+08 3.20000000e+08 2.19317933e+09 1.05723670e+10
 1.12859035e+10 2.00797953e+13 1.05222509e+10 4.03301155e+08
 9.20610980e+08 3.07256110e+07 6.00000000e+07 9.99995700e+09
 2.10000000e+09 1.97721965e+09 8.45142331e+09 2.00000000e+08
 1.50000000e+09 1.34000000e+08 1.33993033e+08 5.81404224e+08
 2.00317147e+10 1.21341166e+06 1.26610009e+08 2.26846935e+07
 1.57838772e+09 9.99803900e+06 1.94242028e+09 2.00000000e+09
 3.88549766e+09 1.15843690e+08 9.97733791e+08 3.00000000e+09
 2.10000000e+10 1.14500000e+08 3.57142860e+07 9.99995801e+08
 1.13321055e+08 9.97376019e+08 1.13057890e+08 2.03672952e+14
 1.68884857e+06 1.87669421e+08 9.41086514e+09 5.85969637e+06
 1.05971760e+08 9.62393068e+08 1.54457131e+07 9.58342751e+08
 9.94167817e+05 1.00198001e+05 8.80028727e+08 5.72301922e+08
 1.00124199e+08 4.43621551e+10 9.53973324e+08 1.92500000e+07
 1.29363102e+09 4.65795273e+06 3.99999949e+09 3.43597384e+10
 5.59844754e+08 9.99999957e+08 8.59739196e+04 4.20000000e+10
 9.99993477e+07 1.18400000e+03 9.77490912e+07 4.98612936e+10
 9.88236613e+10 1.84600686e+10 1.07822406e+08 1.67937672e+08
 2.50000000e+07 8.01782489e+07 2.39996376e+10 1.00000000e+14
 1.95050504e+04 9.99999393e+08 8.56904131e+07 9.99999985e+08
 1.04554816e+07 7.49995411e+07 3.05455370e+06 3.66660000e+04
 8.39188802e+07 2.07507363e+06 9.69073134e+08 3.23895399e+10
 8.69672484e+07 5.84701847e+10 6.50935805e+07 6.80859176e+07
 4.05380800e+11 7.88856124e+07 5.59186993e+06 7.67220806e+07
 1.04460000e+07 1.27649810e+09 7.62026396e+07 7.55686340e+07
 4.20000000e+17 9.97478701e+10 7.51861414e+07 7.50000000e+07
 8.89897671e+09 5.94939130e+08 9.99999999e+08 7.41111616e+07
 6.88578338e+07 1.35784439e+06 3.73851733e+08 1.87868246e+07
 4.96889545e+07 9.99982719e+08 1.63311784e+04 6.46971796e+07
 1.95394080e+09 2.91514754e+08 5.00000000e+09 7.45775268e+09
 5.37153036e+05 9.99961859e+08 9.01841822e+04 9.65045993e+07
 9.99999819e+09 6.90000000e+10 1.09998736e+10 1.03192856e+09
 1.77619434e+11 7.15938165e+10 6.62353808e+07 6.69620403e+07
 6.64487456e+07 1.06002408e+07 6.66666666e+08 1.05702157e+09
 9.99999977e+10 6.53000000e+07 1.02868118e+08 6.52203130e+07
 2.50000000e+08 1.10076274e+10 3.10882500e+11 5.76715130e+07
 4.28758864e+05 6.89996596e+10 9.94552574e+08 4.44138109e+09
 5.58395399e+08 6.10031354e+07 7.88123141e+08 3.70055980e+04
 3.60137968e+09 1.76923512e+14 3.32000000e+09 9.98384105e+08
 5.78590410e+07 5.71323810e+07 1.08284694e+09 9.99999099e+08
 2.37697045e+07 2.05712357e+10 9.98769544e+08 8.80548244e+09
 2.66443386e+05 9.90960442e+09 2.97451079e+07 2.02013142e+09
 5.49941613e+07 1.25323976e+09 5.03128597e+10 7.00000000e+08
 9.00000000e+08 5.39575701e+06 8.76092072e+09 7.83929600e+07
 1.33248297e+08 1.19663293e+09 5.33900618e+07 1.09602978e+10
 7.98169426e+08 2.97959666e+09 2.71892858e+08 5.99999997e+08
 9.79978670e+08 9.96888287e+08 3.99796758e+06 4.20690000e+11
 2.04800000e+09 2.89266386e+06 5.00142299e+07 9.99841633e+08
 1.64420903e+10 1.11550000e+10 1.68698990e+09 5.06000000e+07
 4.08138639e+07 5.01543135e+07 5.01161935e+07 5.00000000e+07
 1.02799649e+09 1.46434580e+10 1.39307529e+10 9.85222890e+08
 4.94904091e+07 1.99484176e+09 3.00000000e+07 2.00000000e+14
 1.31556953e+09 1.65550000e+10 9.99999998e+08 5.35096196e+14
 3.99766000e+03 6.42292128e+09 1.99016457e+10 6.02548352e+08
 4.73307489e+07 4.70000000e+07 1.33700000e+09 4.62419208e+07]

In [40]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [53]:
# check Max_Supply columns

#check data type
print("data type:",df['Max_Supply'].dtype)
print("-"*50)

# check missing value
print("missing value:",df['Max_Supply'].isna().sum())
print("-"*50)

#fill  them using median
df['Max_Supply']=df['Max_Supply'].fillna(df['Max_Supply'].median())
print(df['Max_Supply'])

# check zero value
print("zero value:",(df['Max_Supply']==0).sum())
print("-"*50)

## check nagative value
print("nagative value:",(df['Max_Supply'] < 0).sum())
print("-"*50)

# check duplicated
print("duplicated:",df['Max_Supply'].duplicated().sum())

data type: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
0      2.100000e+07
1      1.000000e+09
2      1.000000e+09
3      2.000000e+08
4      1.000000e+11
           ...
495    1.000000e+09
496    1.337000e+09
497    1.000000e+09
498    1.000000e+10
499    1.000000e+11
Name: Max_Supply, Length: 500, dtype: float64
zero value: 0
--------------------------------------------------
nagative value: 0
--------------------------------------------------
duplicated: 394

In [59]:
# check Ath columns

#check data type
print("datatype:",df['Ath'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Ath'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Ath']==0).sum())
print("-"*50)

## check nagative value
print("nagative value:",(df['Ath'] < 0).sum())
print("-"*50)

datatype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
nagative value: 0
--------------------------------------------------

In [61]:
# check Ath_Change_Percentage columns
#check data type
print("datatype:",df['Ath_Change_Percentage'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Ath_Change_Percentage'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Ath_Change_Percentage']==0).sum())
print("-"*50)

## check nagative value
print("nagative value:",(df['Ath_Change_Percentage'] < 0).sum())
print("-"*50)

datatype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 27
--------------------------------------------------
nagative value: 472
--------------------------------------------------

In [71]:
# check Ath_Date columns

#check data type
print("datatype:",df['Ath_Date'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Ath_Date'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Ath_Date']==0).sum())
print("-"*50)

# convert data time  value
df['Ath_Date']=pd.to_datetime(df['Ath_Date'],errors="coerce")
print("unique:",df['Ath_Date'])
print("-"*50)

# remove space 
df['Ath_Date']=df['Ath_Date'].astype(str).str.strip()
print(df['Ath_Date'])

datatype: datetime64[ns, UTC]
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
unique: 0     2025-10-06 10:57:42+00:00
1     2025-08-24 11:21:03+00:00
2     2018-07-23 16:00:00+00:00
3     2025-10-13 00:41:24+00:00
4     2025-07-17 19:40:53+00:00
                 ...
495   2026-07-04 00:03:20+00:00
496   2025-06-11 10:05:28+00:00
497   2026-01-10 20:35:54+00:00
498   2024-03-28 15:20:10+00:00
499   2025-08-27 18:22:49+00:00
Name: Ath_Date, Length: 500, dtype: datetime64[ns, UTC]
--------------------------------------------------
0      2025-10-06 10:57:42+00:00
1      2025-08-24 11:21:03+00:00
2      2018-07-23 16:00:00+00:00
3      2025-10-13 00:41:24+00:00
4      2025-07-17 19:40:53+00:00
                 ...
495    2026-07-04 00:03:20+00:00
496    2025-06-11 10:05:28+00:00
497    2026-01-10 20:35:54+00:00
498    2024-03-28 15:20:10+00:00
499    2025-08-27 18:22:49+00:00
Name: Ath_Date, Length: 500, dtype: object

In [72]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Roi',
       'Last_Updated'],
      dtype='object')

In [73]:
#check Atl columns
#check data type
print("datatype:",df['Atl'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Atl'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Atl']==0).sum())
print("-"*50)

## check nagative value
print("nagative value:",(df['Atl'] < 0).sum())
print("-"*50)

datatype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
nagative value: 0
--------------------------------------------------

In [76]:
# check Atl_Change_Percentage this columns
#check data type
print("datatype:",df['Atl_Change_Percentage'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Atl_Change_Percentage'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Atl_Change_Percentage']==0).sum())
print("-"*50)

## check nagative value
print("nagative value:",(df['Atl_Change_Percentage'] < 0).sum())
print("-"*50)

datatype: float64
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 18
--------------------------------------------------
nagative value: 0
--------------------------------------------------

In [80]:
# check Atl_Date columns
# Check Atl_Date column

# Check data type
print("datatype:", df['Atl_Date'].dtype)
print("-"*50)

# Check missing value
print("missing value:", df['Atl_Date'].isna().sum())
print("-"*50)

# Check zero value
print("zero value:", (df['Atl_Date'] == 0).sum())
print("-"*50)

# Convert to datetime
df['Atl_Date'] = pd.to_datetime(df['Atl_Date'], errors="coerce")

print("datatype after conversion:", df['Atl_Date'].dtype)
print("-"*50)

# Check missing values after conversion
print("missing after conversion:", df['Atl_Date'].isna().sum())
print("-"*50)

# Check unique dates
print("unique values:", df['Atl_Date'].nunique())

datatype: datetime64[ns, UTC]
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
datatype after conversion: datetime64[ns, UTC]
--------------------------------------------------
missing after conversion: 0
--------------------------------------------------
unique values: 467

In [85]:
# check Roi columns
#check data type
print("datatype:",df['Roi'].dtype)
print("-"*50)

#check missing value
print("missing value:",df['Roi'].isna().sum())
print("-"*50)

# check zero value
print("zero value:",(df['Roi']==0).sum())
print("-"*50)

# derop this columns
df.drop('Roi', axis=1, inplace=True)

datatype: object
--------------------------------------------------
missing value: 460
--------------------------------------------------
zero value: 0
--------------------------------------------------

In [87]:
df.columns

Index(['Id', 'Symbol', 'Name', 'Image', 'Current_Price', 'Market_Cap',
       'Market_Cap_Rank', 'Fully_Diluted_Valuation', 'Total_Volume',
       'High_24H', 'Low_24H', 'Price_Change_24H',
       'Price_Change_Percentage_24H', 'Market_Cap_Change_24H',
       'Market_Cap_Change_Percentage_24H', 'Circulating_Supply',
       'Total_Supply', 'Max_Supply', 'Ath', 'Ath_Change_Percentage',
       'Ath_Date', 'Atl', 'Atl_Change_Percentage', 'Atl_Date', 'Last_Updated'],
      dtype='object')

In [91]:
# Check Last_Updated column

print("datatype:", df['Last_Updated'].dtype)
print("-"*50)

print("missing value:", df['Last_Updated'].isna().sum())
print("-"*50)

print("zero value:", (df['Last_Updated'] == 0).sum())
print("-"*50)

print("unique values:", df['Last_Updated'].nunique())

datatype: object
--------------------------------------------------
missing value: 0
--------------------------------------------------
zero value: 0
--------------------------------------------------
unique values: 16

In [90]:
df['Last_Updated']

0      2026-09-06T12:25:20.000Z
1      2026-09-06T12:25:20.000Z
2      2026-09-06T12:25:20.000Z
3      2026-09-06T12:25:20.000Z
4      2026-09-06T12:25:20.000Z
                 ...
495    2026-09-06T12:27:20.000Z
496    2026-09-06T12:27:20.000Z
497    2026-09-06T12:27:20.000Z
498    2026-09-06T12:27:20.000Z
499    2026-09-06T12:27:20.000Z
Name: Last_Updated, Length: 500, dtype: object

In [92]:
df.to_csv("clean_crypto_data.csv")